# Phase 1 - Week 1 - Lesson Day 2
## NumPy Basics

Full explanations and definitions are in `Day2 Numpy Basics.pdf`. This notebook is for practicing the code and completing the exercise. Every code cell has comments explaining what each line does.

**Sections:**
1. Creating arrays
2. Indexing and slicing
3. Shape and reshaping
4. Exercise - Part A (creating arrays)
5. Exercise - Part B (indexing and slicing)
6. Exercise - Part C (shape and reshaping)

In [ ]:
import numpy as np   # 'np' is the standard alias used everywhere in data science

---
## 1. Creating Arrays - Worked Examples

In [2]:
# 1D array -> built from a plain Python list, a single row of numbers
import numpy as np  # make sure NumPy is available in this cell
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# 2D array -> a list of lists, like rows and columns in a table
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# 3D array -> a list of 2D arrays stacked together
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Built-in shortcuts for creating common arrays without typing every value

zeros = np.zeros((2, 3))          # 2x3 array filled entirely with 0
print(zeros)

ones = np.ones((3, 3))            # 3x3 array filled entirely with 1
print(ones)

range_arr = np.arange(0, 10, 2)   # like range(start, stop, step) but returns an array -> [0, 2, 4, 6, 8]
print(range_arr)

lin_arr = np.linspace(0, 1, 5)    # 5 evenly spaced numbers between 0 and 1 (inclusive)
print(lin_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


---
## 2. Indexing and Slicing - Worked Examples

In [4]:
# 1D indexing and slicing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])     # first element -> 10
print(arr[-1])    # last element -> 50
print(arr[1:4])   # slice from index 1 up to (not including) index 4 -> [20, 30, 40]

10
50
[20 30 40]


In [ ]:
# 2D indexing: matrix[row, column]
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print(matrix[0, 1])   # row 0, column 1 -> 2
print(matrix[:, 0])   # ':' means 'all rows' -> column 0 only -> [1, 4, 7]
print(matrix[1, :])   # row 1, ':' means 'all columns' -> [4, 5, 6]

---
## 3. Shape and Reshaping - Worked Examples

In [ ]:
arr = np.arange(12)          # [0, 1, ..., 11] -> a 1D array of 12 numbers
print(arr.shape)             # (12,) -> one dimension, 12 elements

matrix = arr.reshape(3, 4)   # reshape into 3 rows, 4 columns (3 x 4 = 12, matches original count)
print(matrix.shape)          # (3, 4)
print(matrix)

---
## 4. Exercise - Part A: Creating Arrays (3 questions)

In [ ]:
# 1. Create a 3x3 matrix with numbers 1 through 9 filled in row by row, then print it
# 'np.arange(1, 10)' gives numbers 1 through 9.
# The number 10 is not included.
numbers = np.arange(1, 10)

# Arrange the 9 numbers into 3 rows and 3 columns.
# A 3x3 matrix needs 9 values.
matrix_3x3 = numbers.reshape(3, 3)

# print() shows the matrix on the screen.
print(matrix_3x3)


In [5]:
# 2. Create a 4x2 ar
# 'np.arange(1, 9)' gives numbers 1 through 8.
# The number 9 is not included.
numbers_4x2 = np.arange(1, 9)

# Arrange the 8 numbers into 4 rows and 2 columns.
# A 4x2 array needs 8 values.
array_4x2 = numbers_4x2.reshape(4, 2)

# print() shows the array on the screen.
print(array_4x2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# 3. Create an array of even numbers from 0 to 20 using arange(),

#    and a separate array of 10 evenly spaced numbers between 0 and 100 using linspace()
# 'np.arange(0, 21, 2)' starts at 0.
# The number 21 is not included, so 20 is included.
# '2' means count by 2.
even_numbers = np.arange(0, 21, 2)

# Create 10 evenly spaced numbers from 0 to 100.
# '10' tells NumPy how many numbers to create.
# Both 0 and 100 are included.
spaced_numbers = np.linspace(0, 100, 10)

# print() shows both arrays on the screen.
print(even_numbers)
print(spaced_numbers)

Even numbers from 0 to 20:
[ 0  2  4  6  8 10 12 14 16 18 20]

10 evenly spaced numbers between 0 and 100:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


---
## 5. Exercise - Part B: Indexing and Slicing (4 questions)

In [8]:
# 4. Create an array of numbers 0 to 19 using arange(), then slice out index 5 through index 14

# 'np.arange(20)' starts at 0.
# The number 20 is not included.
numbers = np.arange(20)

# Select indexes 5 through 14.
# The ending index 15 is not included,
# so index 14 is the last selected number.
selected_numbers = numbers[5:15]

# print() shows the selected numbers.
print(selected_numbers)


[ 5  6  7  8  9 10 11 12 13 14]


In [ ]:
# 5. Using the 3x3 matrix from Question 1, print the entire second row, then the entire third column

# Print the entire second row.
# Python starts counting from 0, so the second row is index 1.
# ':' means select all columns.
print(matrix_3x3[1, :])

# Print the entire third column.
# The third column is index 2 because counting starts from 0.
# ':' means select all rows.
print(matrix_3x3[:, 2])



In [ ]:
# 6. Using the same 3x3 matrix, print the value in the middle of the grid (row 1, column 1)

# Print the value in the middle of the matrix.
# Row 1 means the second row because Python starts counting at 0.
# Column 1 means the second column.
print(matrix_3x3[1, 1])


In [ ]:
# 7. Given an array of numbers 1 to 10, print it in reverse order
#    Hint: think about slicing with a negative step, e.g. array[::-1]

# Create an array containing numbers 1 through 10.
# The number 11 is not included.
numbers_1_to_10 = np.arange(1, 11)

# Reverse the array.
# '::-1' means start at the end and move backward by 1.
reversed_numbers = numbers_1_to_10[::-1]

# print() shows the reversed array.
print(reversed_numbers)


---
## 6. Exercise - Part C: Shape and Reshaping (3 questions)

In [ ]:
# 8. Create an array using arange(1, 16) (numbers 1 to 15) and print its shape

# The number 16 is not included.
numbers_1_to_15 = np.arange(1, 16)

# .shape tells us the array's dimensions.
# (15,) means one dimension containing 15 numbers.
print(numbers_1_to_15.shape)

In [ ]:
# 9. Reshape that same array of 15 numbers into a 3x5 matrix, and separately into a 5x3 matrix
#    Print both and compare how the numbers are arranged differently

# Reshape the 15 numbers into 3 rows and 5 columns.
# 3 x 5 = 15, so all numbers fit.
matrix_3x5 = numbers_1_to_15.reshape(3, 5)

# Reshape the same numbers into 5 rows and 3 columns.
# 5 x 3 = 15, so all numbers fit.
matrix_5x3 = numbers_1_to_15.reshape(5, 3)

# Print both matrices.
print(matrix_3x5)
print(matrix_5x3)


In [ ]:
# 10. Try reshaping the 15-number array into a (4, 4) shape and observe the error
#     Write one comment line explaining why it failed

# A 4x4 matrix needs 16 values, but this array contains only 15.
matrix_4x4 = numbers_1_to_15.reshape(4, 4)

# print() shows the matrix on the screen.
print(matrix_4x4)   


ValueError: cannot reshape array of size 15 into shape (4,4)