# Phase 1 - Week 1 - Lesson Day 3
## NumPy Operations

Full explanations and definitions are in `Day3 Numpy Operations.pdf`. This notebook is for practicing the code and completing the exercise. Every code cell has comments explaining what each line does.

**Sections:**
1. Vectorized operations
2. Broadcasting
3. Aggregate functions
4. Boolean masking
5. Exercise - Part A (vectorized ops & broadcasting)
6. Exercise - Part B (aggregate functions)
7. Exercise - Part C (boolean masking)

In [3]:
import numpy as np

---
## 1. Vectorized Operations - Worked Examples

In [ ]:
arr = np.array([1, 2, 3, 4])

# Slow way: looping through manually and appending to a list
doubled_slow = []
for x in arr:
    doubled_slow.append(x * 2)
print(doubled_slow)

# Fast way: vectorized -> the operation is applied to every element automatically
doubled_fast = arr * 2
print(doubled_fast)

In [ ]:
# More vectorized operations - all applied to every element at once, no loop needed
print(arr + 5)    # add 5 to every element
print(arr - 2)    # subtract 2 from every element
print(arr ** 2)   # square every element

---
## 2. Broadcasting - Worked Example

In [ ]:
# Broadcasting: a smaller array is 'stretched' to match a bigger array's shape
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])
row = np.array([10, 20, 30])   # matches the number of columns (3)

result = matrix + row   # row gets added to EVERY row of the matrix
print(result)

---
## 3. Aggregate Functions - Worked Examples

In [ ]:
arr = np.array([4, 8, 15, 16, 23, 42])

print(arr.sum())    # total of all values
print(arr.mean())   # average value
print(arr.std())    # standard deviation - how spread out the values are
print(arr.min())    # smallest value
print(arr.max())    # largest value

In [ ]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6]])

print(matrix.sum(axis=0))   # axis=0 -> sum DOWN each column -> [5, 7, 9]
print(matrix.sum(axis=1))   # axis=1 -> sum ACROSS each row  -> [6, 15]

---
## 4. Boolean Masking - Worked Examples

In [ ]:
arr = np.array([10, 15, 20, 25, 30])

mask = arr > 18          # creates an array of True/False values
print(mask)
print(arr[mask])         # keep only the values where mask is True

# usually written in one line, without a separate mask variable:
print(arr[arr > 18])

In [ ]:
# combining multiple conditions with & (and) / | (or) - each condition needs its own parentheses
print(arr[(arr > 12) & (arr < 28)])   # greater than 12 AND less than 28

---
## 5. Exercise - Part A: Vectorized Operations & Broadcasting (3 questions)
No loops allowed in any of these - vectorized only.

In [4]:
# 1. Apply a 20% discount to every price below in one vectorized line
prices = np.array([100, 250, 75, 300, 50])  # Store the original prices in a NumPy array

discount_rate = 0.20  # Store 20% as a decimal value
remaining_rate = 1 - discount_rate  # Calculate the 80% that remains after the discount

discounted_prices = prices * remaining_rate  # Multiply every price by 80% at the same time
print(discounted_prices)  # Display the prices after the discount

[ 80. 200.  60. 240.  40.]


In [5]:
# 2. Convert the Celsius temperatures below to Fahrenheit: (C * 9/5) + 32
celsius = np.array([0, 15, 30, 45])  # Store the temperatures in Celsius

fahrenheit = (celsius * 9 / 5) + 32  # Convert every Celsius value to Fahrenheit at once
print(fahrenheit)  # Display the converted temperatures

[ 32.  59.  86. 113.]


In [6]:
# 3. Add a flat bonus of 500 to every value in this 3x2 sales array using broadcasting
sales = np.array([[1000, 1200],
                   [900, 1100],
                   [1500, 1600]])  # Store the sales values in a 3-row by 2-column array

sales_with_bonus = sales + 500  # Add 500 to every value using broadcasting
print(sales_with_bonus)  # Display the sales values after adding the bonus

[[1500 1700]
 [1400 1600]
 [2000 2100]]


---
## 6. Exercise - Part B: Aggregate Functions (3 questions)

In [7]:
# 4. Calculate and print the sum, mean, min, and max of this sales array
sales_data = np.array([120, 340, 210, 90, 450, 380, 275, 190, 310, 260])  # Store the sales values

total_sales = sales_data.sum()  # Add all sales values together
average_sales = sales_data.mean()  # Calculate the average sales value
lowest_sales = sales_data.min()  # Find the smallest sales value
highest_sales = sales_data.max()  # Find the largest sales value

print(total_sales)  # Display the total sales
print(average_sales)  # Display the average sales
print(lowest_sales)  # Display the smallest sales value
print(highest_sales)  # Display the largest sales value

2625
262.5
90
450


In [8]:
# 5. Calculate the total per product (row) and total per week (column)
weekly_sales = np.array([[10, 20, 30, 40],
                          [15, 25, 35, 45],
                          [5, 10, 15, 20]])  # Store weekly sales for each product

product_totals = weekly_sales.sum(axis=1)  # Add across each row to get each product total
week_totals = weekly_sales.sum(axis=0)  # Add down each column to get each week total

print(product_totals)  # Display the total for each product
print(week_totals)  # Display the total for each week

[100 120  50]
[ 30  55  80 105]


In [9]:
# 6. Calculate the standard deviation of both score groups below
#    then write a comment stating which group is more spread out
group_a = np.array([70, 72, 68, 75, 71])  # Store the scores for group A
group_b = np.array([50, 90, 40, 95, 60])  # Store the scores for group B

standard_deviation_a = group_a.std()  # Calculate how spread out group A is
standard_deviation_b = group_b.std()  # Calculate how spread out group B is

print(standard_deviation_a)  # Display group A's standard deviation
print(standard_deviation_b)  # Display group B's standard deviation
# Group B is more spread out because its standard deviation is larger.

2.3151673805580453
21.817424229271428


---
## 7. Exercise - Part C: Boolean Masking (4 questions)

In [10]:
# 7. Calculate the mean of this sales array, then print only the values ABOVE the mean
sales2 = np.array([200, 450, 120, 300, 600, 90, 275])  # Store the sales values

sales_mean = sales2.mean()  # Calculate the average sales value
sales_above_mean = sales2[sales2 > sales_mean]  # Keep only values greater than the mean

print(sales_mean)  # Display the mean sales value
print(sales_above_mean)  # Display the sales values above the mean

290.7142857142857
[450 300 600]


In [11]:
# 8. Print only the scores that are >= 60 (a 'pass' threshold)
scores = np.array([45, 62, 88, 59, 73, 40, 91])  # Store the student scores

passing_scores = scores[scores >= 60]  # Keep scores that are greater than or equal to 60
print(passing_scores)  # Display the passing scores

[62 88 73 91]


In [12]:
# 9. Print only the ages between 18 and 30 (inclusive) using a combined condition
ages = np.array([15, 22, 35, 28, 17, 30, 45, 19])  # Store the ages

ages_in_range = ages[(ages >= 18) & (ages <= 30)]  # Keep ages from 18 through 30, including both limits
print(ages_in_range)  # Display the ages in the requested range

[22 28 30 19]


In [13]:
# 10. Count how many temperatures are above 25 degrees
#     Hint: a boolean mask summed with .sum() counts the True values (True = 1, False = 0)
temps = np.array([22, 28, 19, 31, 26, 24, 33])  # Store the temperatures

temperatures_above_25 = temps > 25  # Create True/False values for temperatures above 25
number_above_25 = temperatures_above_25.sum()  # Count the True values

print(number_above_25)  # Display how many temperatures are above 25

4
