# Phase 1 - Week 1 - Lesson Day 4
## NumPy Applied + Week 1 Mini Challenge

Full explanations and definitions are in `Day4 Numpy Applied.pdf`. This notebook is for practicing the code and completing the exercise. Every code cell has comments explaining what each line does.

**Sections:**
1. Random number generation
2. Combining and stacking arrays
3. Dot product and matrix multiplication
4. Exercise - Part A (random numbers & stacking)
5. Exercise - Part B (dot product & matrix multiplication)
6. Exercise - Part C (Week 1 Mini Challenge)

In [1]:
import numpy as np

---
## 1. Random Number Generation - Worked Examples

In [ ]:
np.random.seed(42)   # locks in a fixed 'random' sequence so results are reproducible

random_ints = np.random.randint(1, 100, size=10)   # 10 random integers between 1 and 99
print(random_ints)

random_floats = np.random.rand(5)   # 5 random floats between 0 and 1
print(random_floats)

random_normal = np.random.normal(loc=50, scale=10, size=100)   # 100 values, normal distribution
print(random_normal[:10])   # just show the first 10 to keep the output short

---
## 2. Combining and Stacking Arrays - Worked Examples

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.concatenate([a, b]))   # joins 1D arrays end to end -> [1, 2, 3, 4, 5, 6]
print(np.vstack([a, b]))        # stacks vertically -> creates a 2x3 matrix (new rows)
print(np.hstack([a, b]))        # stacks horizontally -> [1, 2, 3, 4, 5, 6] for 1D arrays

---
## 3. Dot Product & Matrix Multiplication - Worked Examples

In [ ]:
# Dot product of two 1D arrays: multiply corresponding elements, then sum the results
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))   # (1*4) + (2*5) + (3*6) = 32

In [ ]:
# Matrix multiplication: rows of matrix_a combined with columns of matrix_b
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
print(np.dot(matrix_a, matrix_b))

---
## 4. Exercise - Part A: Random Numbers & Stacking (4 questions)

In [2]:
# Choose a seed number.
np.random.seed(7)

# Create 15 random whole numbers from 1 to 100.
numbers = np.random.randint(1, 101, 15)

# Print the numbers.
print(numbers)

# Run this cell again. The numbers will be the same because we used the same seed.

[48 69 26 68 84 24 93 58 15 24 73 90 43 91  9]


In [3]:
# Create 50 random scores.
# The scores are centered around 70, with a standard deviation of 8.
scores = np.random.normal(70, 8, 50)

# Find and print the average score.
average_score = np.mean(scores)
print("Average:", average_score)

# Find and print how spread out the scores are.
score_spread = np.std(scores)
print("Standard deviation:", score_spread)

Average: 69.24234772720092
Standard deviation: 9.005916310193676


In [4]:
# Make the first list of 4 numbers.
first_array = np.array([1, 2, 3, 4])

# Make the second list of 4 numbers.
second_array = np.array([5, 6, 7, 8])

# Put the two arrays on top of each other.
vertical_array = np.vstack((first_array, second_array))

# Print the result.
print(vertical_array)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
# Join the two arrays from Question 3 side by side.
horizontal_array = np.hstack((first_array, second_array))

# Print the result.
print(horizontal_array)

# The vertical array has 2 rows and 4 columns.
print("Vertical shape:", vertical_array.shape)

# The horizontal array has 8 numbers in one row.
print("Horizontal shape:", horizontal_array.shape)

[1 2 3 4 5 6 7 8]
Vertical shape: (2, 4)
Horizontal shape: (8,)


---
## 5. Exercise - Part B: Dot Product & Matrix Multiplication (2 questions)

In [6]:
# Make the first array.
a = np.array([2, 4, 6])

# Make the second array.
b = np.array([1, 3, 5])

# By hand: (2 * 1) + (4 * 3) + (6 * 5) = 44

# Ask NumPy to calculate the dot product.
answer = np.dot(a, b)
print(answer)

44


In [7]:
# Make the first 2 by 2 matrix.
first_matrix = np.array([[1, 2], [3, 4]])

# Make the second 2 by 2 matrix.
second_matrix = np.array([[5, 6], [7, 8]])

# Multiply the two matrices.
answer = np.dot(first_matrix, second_matrix)

# Print the answer.
print(answer)

[[19 22]
 [43 50]]


---
## 6. Exercise - Part C: Week 1 Mini Challenge (Simulated Test Scores)

Combines Day 2, Day 3, and Day 4 material. No loops allowed - vectorized operations only.

Follow the steps below **in order** - each one builds on the previous step's result.

In [8]:
# Choose a seed number.
np.random.seed(21)

# This makes our random scores the same every time we run the cells.

In [9]:
# Make 100 random test scores.
# The lowest possible score is 0 and the highest possible score is 100.
test_scores = np.random.randint(0, 101, 100)

# Print the scores.
print(test_scores)

[ 73  79  56   4  48  35  60  98  74  72  63  44  61  48 100  84  59  20
  76  56  41   5  18  70  50  56  98  48  53   5  80  35  91  33  12  82
  15   6  84  90  28   9  80   0   5  69  57  99   4  76  30  30  76  25
  32  90  32  63  25  79  53  66  71  33   8  58  50  94  24  25  64  25
  92  78  47  39   5  43  18  39  96   4  34  50  96  57  16  99   1  51
   1  27  33  32  31  66  86  74  93  89]


In [10]:
# Find the average score.
average_score = np.mean(test_scores)
print("Average:", average_score)

# Find the standard deviation.
score_spread = np.std(test_scores)
print("Standard deviation:", score_spread)

# Find the lowest score.
lowest_score = np.min(test_scores)
print("Lowest score:", lowest_score)

# Find the highest score.
highest_score = np.max(test_scores)
print("Highest score:", highest_score)

Average: 50.59
Standard deviation: 29.362593550297973
Lowest score: 0
Highest score: 100


In [11]:
# Make a True/False list.
# True means the score is greater than 60.
passed = test_scores > 60

# Keep only the scores where passed is True.
passing_scores = test_scores[passed]

# Print the passing scores.
print(passing_scores)

[ 73  79  98  74  72  63  61 100  84  76  70  98  80  91  82  84  90  80
  69  99  76  76  90  63  79  66  71  94  64  92  78  96  96  99  66  86
  74  93  89]


In [12]:
# Count how many True values are in the passed list.
# Each True value represents one student who passed.
number_passed = np.sum(passed)

# Print the number of students who passed.
print("Students who passed:", number_passed)

Students who passed: 39


In [13]:
# Count all the scores.
total_students = len(test_scores)

# Divide the number who passed by the total number.
passing_percentage = number_passed / total_students * 100

# Print the percentage.
print("Percentage who passed:", passing_percentage, "%")

Percentage who passed: 39.0 %
